/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultantsRouteImport } from './routes/_authenticated/consultants'
import { Route as AuthenticatedBotRouteImport } from './routes/_authenticated/bot'
import { Route as AuthenticatedPortfolioIndexRouteImport } from './routes/_authenticated/portfolio.index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsSlackRouteImport } from './routes/_authenticated/settings.slack'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsHubspotRouteImport } from './routes/_authenticated/settings.hubspot'
import { Route as AuthenticatedPortfolioNewRouteImport } from './routes/_authenticated/portfolio.new'
import { Route as AuthenticatedPortfolioAgencyIdRouteImport } from './routes/_authenticated/portfolio.$agencyId'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicSlackInteractionsRouteImport } from './routes/api/public/slack.interactions'
import { Route as ApiPublicSlackHealthRouteImport } from './routes/api/public/slack.health'
import { Route as ApiPublicSlackEventsRouteImport } from './routes/api/public/slack.events'
import { Route as ApiPublicSlackCronRouteImport } from './routes/api/public/slack.cron'
import { Route as ApiPublicSlackCommandsRouteImport } from './routes/api/public/slack.commands'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultantsRoute =
  AuthenticatedConsultantsRouteImport.update({
    id: '/consultants',
    path: '/consultants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotRoute = AuthenticatedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioIndexRoute =
  AuthenticatedPortfolioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSlackRoute =
  AuthenticatedSettingsSlackRouteImport.update({
    id: '/settings/slack',
    path: '/settings/slack',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsHubspotRoute =
  AuthenticatedSettingsHubspotRouteImport.update({
    id: '/settings/hubspot',
    path: '/settings/hubspot',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioNewRoute =
  AuthenticatedPortfolioNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const AuthenticatedPortfolioAgencyIdRoute =
  AuthenticatedPortfolioAgencyIdRouteImport.update({
    id: '/$agencyId',
    path: '/$agencyId',
    getParentRoute: () => AuthenticatedPortfolioRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSlackInteractionsRoute =
  ApiPublicSlackInteractionsRouteImport.update({
    id: '/api/public/slack/interactions',
    path: '/api/public/slack/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSlackHealthRoute = ApiPublicSlackHealthRouteImport.update({
  id: '/api/public/slack/health',
  path: '/api/public/slack/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackEventsRoute = ApiPublicSlackEventsRouteImport.update({
  id: '/api/public/slack/events',
  path: '/api/public/slack/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackCronRoute = ApiPublicSlackCronRouteImport.update({
  id: '/api/public/slack/cron',
  path: '/api/public/slack/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackCommandsRoute = ApiPublicSlackCommandsRouteImport.update({
  id: '/api/public/slack/commands',
  path: '/api/public/slack/commands',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bot': typeof AuthenticatedBotRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/portfolio': typeof AuthenticatedPortfolioRouteWithChildren
  '/portfolio/$agencyId': typeof AuthenticatedPortfolioAgencyIdRoute
  '/portfolio/new': typeof AuthenticatedPortfolioNewRoute
  '/settings/hubspot': typeof AuthenticatedSettingsHubspotRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/slack': typeof AuthenticatedSettingsSlackRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/portfolio/': typeof AuthenticatedPortfolioIndexRoute
  '/api/public/slack/commands': typeof ApiPublicSlackCommandsRoute
  '/api/public/slack/cron': typeof ApiPublicSlackCronRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/health': typeof ApiPublicSlackHealthRoute
  '/api/public/slack/interactions': typeof ApiPublicSlackInteractionsRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bot': typeof AuthenticatedBotRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import': typeof AuthenticatedImportRoute
  '/portfolio/$agencyId': typeof AuthenticatedPortfolioAgencyIdRoute
  '/portfolio/new': typeof AuthenticatedPortfolioNewRoute
  '/settings/hubspot': typeof AuthenticatedSettingsHubspotRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/slack': typeof AuthenticatedSettingsSlackRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/portfolio': typeof AuthenticatedPortfolioIndexRoute
  '/api/public/slack/commands': typeof ApiPublicSlackCommandsRoute
  '/api/public/slack/cron': typeof ApiPublicSlackCronRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/health': typeof ApiPublicSlackHealthRoute
  '/api/public/slack/interactions': typeof ApiPublicSlackInteractionsRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/bot': typeof AuthenticatedBotRoute
  '/_authenticated/consultants': typeof AuthenticatedConsultantsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRouteWithChildren
  '/_authenticated/portfolio/$agencyId': typeof AuthenticatedPortfolioAgencyIdRoute
  '/_authenticated/portfolio/new': typeof AuthenticatedPortfolioNewRoute
  '/_authenticated/settings/hubspot': typeof AuthenticatedSettingsHubspotRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/slack': typeof AuthenticatedSettingsSlackRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/portfolio/': typeof AuthenticatedPortfolioIndexRoute
  '/api/public/slack/commands': typeof ApiPublicSlackCommandsRoute
  '/api/public/slack/cron': typeof ApiPublicSlackCronRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
  '/api/public/slack/health': typeof ApiPublicSlackHealthRoute
  '/api/public/slack/interactions': typeof ApiPublicSlackInteractionsRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bot'
    | '/consultants'
    | '/dashboard'
    | '/import'
    | '/portfolio'
    | '/portfolio/$agencyId'
    | '/portfolio/new'
    | '/settings/hubspot'
    | '/settings/profile'
    | '/settings/slack'
    | '/settings/users'
    | '/portfolio/'
    | '/api/public/slack/commands'
    | '/api/public/slack/cron'
    | '/api/public/slack/events'
    | '/api/public/slack/health'
    | '/api/public/slack/interactions'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bot'
    | '/consultants'
    | '/dashboard'
    | '/import'
    | '/portfolio/$agencyId'
    | '/portfolio/new'
    | '/settings/hubspot'
    | '/settings/profile'
    | '/settings/slack'
    | '/settings/users'
    | '/portfolio'
    | '/api/public/slack/commands'
    | '/api/public/slack/cron'
    | '/api/public/slack/events'
    | '/api/public/slack/health'
    | '/api/public/slack/interactions'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/bot'
    | '/_authenticated/consultants'
    | '/_authenticated/dashboard'
    | '/_authenticated/import'
    | '/_authenticated/portfolio'
    | '/_authenticated/portfolio/$agencyId'
    | '/_authenticated/portfolio/new'
    | '/_authenticated/settings/hubspot'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/slack'
    | '/_authenticated/settings/users'
    | '/_authenticated/portfolio/'
    | '/api/public/slack/commands'
    | '/api/public/slack/cron'
    | '/api/public/slack/events'
    | '/api/public/slack/health'
    | '/api/public/slack/interactions'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicSlackCommandsRoute: typeof ApiPublicSlackCommandsRoute
  ApiPublicSlackCronRoute: typeof ApiPublicSlackCronRoute
  ApiPublicSlackEventsRoute: typeof ApiPublicSlackEventsRoute
  ApiPublicSlackHealthRoute: typeof ApiPublicSlackHealthRoute
  ApiPublicSlackInteractionsRoute: typeof ApiPublicSlackInteractionsRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultants': {
      id: '/_authenticated/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof AuthenticatedConsultantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot': {
      id: '/_authenticated/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthenticatedBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio/': {
      id: '/_authenticated/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof AuthenticatedPortfolioIndexRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/slack': {
      id: '/_authenticated/settings/slack'
      path: '/settings/slack'
      fullPath: '/settings/slack'
      preLoaderRoute: typeof AuthenticatedSettingsSlackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/hubspot': {
      id: '/_authenticated/settings/hubspot'
      path: '/settings/hubspot'
      fullPath: '/settings/hubspot'
      preLoaderRoute: typeof AuthenticatedSettingsHubspotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio/new': {
      id: '/_authenticated/portfolio/new'
      path: '/new'
      fullPath: '/portfolio/new'
      preLoaderRoute: typeof AuthenticatedPortfolioNewRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/_authenticated/portfolio/$agencyId': {
      id: '/_authenticated/portfolio/$agencyId'
      path: '/$agencyId'
      fullPath: '/portfolio/$agencyId'
      preLoaderRoute: typeof AuthenticatedPortfolioAgencyIdRouteImport
      parentRoute: typeof AuthenticatedPortfolioRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/interactions': {
      id: '/api/public/slack/interactions'
      path: '/api/public/slack/interactions'
      fullPath: '/api/public/slack/interactions'
      preLoaderRoute: typeof ApiPublicSlackInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/health': {
      id: '/api/public/slack/health'
      path: '/api/public/slack/health'
      fullPath: '/api/public/slack/health'
      preLoaderRoute: typeof ApiPublicSlackHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/events': {
      id: '/api/public/slack/events'
      path: '/api/public/slack/events'
      fullPath: '/api/public/slack/events'
      preLoaderRoute: typeof ApiPublicSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/cron': {
      id: '/api/public/slack/cron'
      path: '/api/public/slack/cron'
      fullPath: '/api/public/slack/cron'
      preLoaderRoute: typeof ApiPublicSlackCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/commands': {
      id: '/api/public/slack/commands'
      path: '/api/public/slack/commands'
      fullPath: '/api/public/slack/commands'
      preLoaderRoute: typeof ApiPublicSlackCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPortfolioRouteChildren {
  AuthenticatedPortfolioAgencyIdRoute: typeof AuthenticatedPortfolioAgencyIdRoute
  AuthenticatedPortfolioNewRoute: typeof AuthenticatedPortfolioNewRoute
  AuthenticatedPortfolioIndexRoute: typeof AuthenticatedPortfolioIndexRoute
}

const AuthenticatedPortfolioRouteChildren: AuthenticatedPortfolioRouteChildren =
  {
    AuthenticatedPortfolioAgencyIdRoute: AuthenticatedPortfolioAgencyIdRoute,
    AuthenticatedPortfolioNewRoute: AuthenticatedPortfolioNewRoute,
    AuthenticatedPortfolioIndexRoute: AuthenticatedPortfolioIndexRoute,
  }

const AuthenticatedPortfolioRouteWithChildren =
  AuthenticatedPortfolioRoute._addFileChildren(
    AuthenticatedPortfolioRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBotRoute: typeof AuthenticatedBotRoute
  AuthenticatedConsultantsRoute: typeof AuthenticatedConsultantsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRouteWithChildren
  AuthenticatedSettingsHubspotRoute: typeof AuthenticatedSettingsHubspotRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSlackRoute: typeof AuthenticatedSettingsSlackRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBotRoute: AuthenticatedBotRoute,
  AuthenticatedConsultantsRoute: AuthenticatedConsultantsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRouteWithChildren,
  AuthenticatedSettingsHubspotRoute: AuthenticatedSettingsHubspotRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSlackRoute: AuthenticatedSettingsSlackRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicSlackCommandsRoute: ApiPublicSlackCommandsRoute,
  ApiPublicSlackCronRoute: ApiPublicSlackCronRoute,
  ApiPublicSlackEventsRoute: ApiPublicSlackEventsRoute,
  ApiPublicSlackHealthRoute: ApiPublicSlackHealthRoute,
  ApiPublicSlackInteractionsRoute: ApiPublicSlackInteractionsRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
